# # subprocess_run_check.py
#
# _____ ?
#
# ___
#     ?.r.. 'false' c.._T..
# _____ ?.C.. __ err
#     print('ERROR:' ?
#
# # $ python3 subprocess_run_check.py
# #
# # ERROR: Command '['false']' returned non-zero exit status 1
