# # -*- coding: utf-8 -*-
#
# print(2 __ [1, 2, 3, 4, 5], 6 __ [1, 2, 3, 4, 5])             # Проверка на вхождение
# # (True, False)
# print(2 ___ __ [1, 2, 3, 4, 5], 6 ___ __ [1, 2, 3, 4, 5])     # Проверка на невхождение
# # (False, True)
#
#
# arr = [1, 2, 1, 2, 1]
# print(?.i... 1, ?.i... 2
# # (0, 1)
# print(?.i... 1, 1 ?.i... 1, 3, 5
# # (2, 4)
# # print(arr.i...(3))
# # Traceback (most recent call last):
# #   File "<pyshell#16>", line 1, in <module>
# #     arr.i...(3)
# # ValueError: 3 is not in list
#
#
# arr = [1, 2, 1, 2, 1]
# print(?.c... 1 ?.c... 2
# # (3, 2)
# print(?.c... 3                  # Элемент не входит в список
# # 0
#
#
# arr = [1, 2, 3, 4, 5]
# print(ma. ? mi. ?
# (5, 1)
#
#
# print(a.. 0, N.. a.. 0, N.., 1  , a.. ||
# # (False, True, False)
#
#
# print(al_ 0, N.. al_ 0, N.. 1, al_ ||, al_ "str", 10
# # (False, False, True, True)